### ISSUE TITLE
您好，我读取时出现以下问题，不知道您这边有没有什么解决方法

### ISSUE THREAD

**Issue by chingxiu** [IncubatorShokuhou/meic2wrf_hourly#5]
![image](https://user-images.githubusercontent.com/95530162/229389428-083d6a6f-45e7-42c0-b5ce-74dc90ede430.png)
[namelist.csv](https://github.com/IncubatorShokuhou/meic2wrf_hourly/files/11133785/namelist.csv)
以上是我的namelist.input和错误截图，请问有朋友知道怎么回事吗，数据里面也是有值的，当我将io_form_auxinput5=2,force_use_old_data=T这个选项去除掉的时候，不会出现上述报错，正常运行，但最终我看了输出，并没有成功读取到排放，有朋友遇到相似的问题了吗

**Comment by chingxiu** [comment]
已解决

**Comment by zebiu** [comment]
> 已解决
你好 我也遇到了这个报错 请问您是怎么解决的呢

**Comment by chingxiu** [comment]
> > 已解决
> > 你好 我也遇到了这个报错 请问您是怎么解决的呢

这个有点久远了，我说一下我的解决办法吧，这个问题应该是人为源排放读取遇到的问题，之前报错namelist设置的是按时间排序的排放文件（日期时间格式），实际上我前面说的未读取排放成功是指它只读取到了第一个排放的文件，后续都没读取到（我也不知道啥原因）；因此，后续我使用的人为源排放文件格式是wrfchemi_00z_d01，wrfchemi_12z_d01类似的格式,这种格式它就能政策读取运行（当然namelist也要相应调整）

**Comment by zebiu** [comment]
![rsl error](https://github.com/IncubatorShokuhou/meic2wrf_hourly/assets/125586828/2e05b23f-56d6-49af-892b-66b747e96511)
[namelist.input.csv](https://github.com/IncubatorShokuhou/meic2wrf_hourly/files/15014471/namelist.input.csv)
感谢您的建议，但是我后续采纳了您的建议后，出现了新的问题，不知道您是否知道如何解决，我用的版本是WRF-chem4.0 MEICv1.3 也是使用meic2wrf进行处理。这里附上我的namelist以及报错。

**Comment by chingxiu** [comment]
> ![rsl error](https://private-user-images.githubusercontent.com/125586828/323302535-2e05b23f-56d6-49af-892b-66b747e96511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzE5MjYsIm5iZiI6MTcxMzM3MTYyNiwicGF0aCI6Ii8xMjU1ODY4MjgvMzIzMzAyNTM1LTJlMDViMjNmLTU2ZDYtNDlhZi04OTJiLTY2Yjc0N2U5NjUxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjMzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2Q2MmVhMjQ1NGZmMGQ3NGJhMGFhMjdiZTQ2NjdmNGYzOTZiNzQxOGYwZTRlNjRlNDQ4ZDY4M2ViY2U4YTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.29trVPcSLxSuI22U5I9FdDnMYIwwOJC5BdetGpj445k) [namelist.input.csv](https://github.com/IncubatorShokuhou/meic2wrf_hourly/files/15014471/namelist.input.csv) 感谢您的建议，但是我后续采纳了您的建议后，出现了新的问题，不知道您是否知道如何解决，我用的版本是WRF-chem4.0 MEICv1.3 也是使用meic2wrf进行处理。这里附上我的namelist以及报错。

你可以尝试设置一下frames_per_auxinput5参数，一般wrfchemi_00z_d01是设置为12，代表读取0时到12时的数据，这是我的namelist，可以参考一下
[namelist.input.csv](https://github.com/IncubatorShokuhou/meic2wrf_hourly/files/15014590/namelist.input.csv)

**Comment by zebiu** [comment]
感谢，已解决，其实是我的编译有问题，重新编译chem就可以了
